import { Claim, CAPA } from './domain';

const now = '2026-09-20T08:00:00Z';
const base = (x: Partial<Claim>): Claim => ({
  id: crypto.randomUUID(),
  claimAgainst: 'Service call',
  callNo: '',
  callDate: '',
  claimDate: '',
  claimNo: '',
  brand: '',
  customerName: '',
  model: '',
  serialNo: '',
  partNo: '',
  description: '',
  qty: 1,
  importInvoiceNo: '',
  importInvoiceDate: '',
  turelTaxInvoiceNo: '',
  turelTaxInvoiceDate: '',
  installationDate: '',
  category: 'Damaged in transit',
  remark: '',
  vendorResponse: 'Pending',
  damagedPartInward: 'N',
  damagedPartGRNNo: '',
  damagedPartGRNDate: '',
  newPartAtHO: 'N',
  hoGRNNo: '',
  hoGRNDate: '',
  claimChallanNo: '',
  challanDate: '',
  newPartAtBranch: 'N',
  branchGRNNo: '',
  branchGRNDate: '',
  turelNewPartOutward: 'N',
  customerReceiptDate: '',
  oemClaimNo: '',
  oemClaimDate: '',
  oemSettlementExpected: '',
  oemClaimOutcome: 'Pending',
  oemReplacementReceived: 'N',
  creditNoteVerified: 'N',
  inventoryAdjusted: 'N',
  financeReceivableCleared: 'N',
  localPurchaseExpenseSettled: 'Y',
  interimOption: '',
  branchTransferRequestNo: '',
  localPO: '',
  localPurchaseGRN: '',
  temporaryLocalPurchaseCost: null,
  oemCreditValue: null,
  rootCauseBrief: '',
  capaNo: '',
  capaStatus: 'N/A',
  isoClauseRef: 'Cl. 8.7',
  createdAt: now,
  updatedAt: now,
  source: 'DEMO',
  ...x
});

export const demoClaims: Claim[] = [
  base({
    id: 'claim-demo-001',
    claimAgainst: 'Installation call',
    callNo: 'IC/MUM/25-26/AMC/000145',
    callDate: '2026-01-14',
    claimDate: '2026-01-16',
    claimNo: 'CLM-TSC-LDH-TY-25-26-001',
    brand: 'Typical',
    customerName: 'Anandco Sporting Corporation',
    model: 'GC20606-1',
    serialNo: '21070001',
    partNo: 'OIL-TNK-01',
    description: 'Oil Tank Assembly',
    category: 'Damaged in transit',
    vendorResponse: 'Approved',
    damagedPartInward: 'Y',
    damagedPartGRNNo: 'GRN-001',
    damagedPartGRNDate: '2026-01-17',
    newPartAtHO: 'Y',
    hoGRNNo: 'GRN-HO-5876',
    hoGRNDate: '2026-02-05',
    claimChallanNo: 'DN2-2627/MUM1003',
    challanDate: '2026-08-19',
    newPartAtBranch: 'Y',
    branchGRNNo: 'GRN-BR-1234',
    branchGRNDate: '2026-08-25',
    turelNewPartOutward: 'Y',
    customerReceiptDate: '2026-09-20',
    oemClaimNo: 'OEM-TY-2425-001',
    oemClaimDate: '2026-01-16',
    oemSettlementExpected: 'Replacement',
    oemClaimOutcome: 'Settled',
    oemReplacementReceived: 'Y',
    creditNoteVerified: 'Y',
    inventoryAdjusted: 'Y',
    financeReceivableCleared: 'Y',
    localPurchaseExpenseSettled: 'Y',
    interimOption: 'A',
    oemCreditValue: 18500,
    capaNo: 'CAPA-001',
    capaStatus: 'Closed',
    isoClauseRef: 'Cl. 8.7 / 10.2',
    auditLogs: [
      { id: 'log-101', timestamp: '2026-01-16 09:30:00', user: 'Service Head', action: 'Claim Created', previousValue: 'N/A', newValue: 'Draft Created' },
      { id: 'log-102', timestamp: '2026-01-16 11:15:00', user: 'QMS Auditor', action: 'OEM Claim Number Added', previousValue: 'Empty', newValue: 'OEM-TY-2425-001' },
      { id: 'log-103', timestamp: '2026-01-17 14:00:00', user: 'Stores Manager', action: 'Damaged Part Inward GRN', previousValue: 'N', newValue: 'GRN-001' },
      { id: 'log-104', timestamp: '2026-02-05 16:45:00', user: 'HO Stores', action: 'OEM Replacement Received', previousValue: 'Pending', newValue: 'GRN-HO-5876' },
      { id: 'log-105', timestamp: '2026-08-20 10:20:00', user: 'Finance Officer', action: 'Finance Receivable Cleared', previousValue: 'Pending', newValue: 'Cleared (INR 18,500)' },
      { id: 'log-106', timestamp: '2026-09-20 17:00:00', user: 'QMS Lead', action: 'Claim Closed (All Gates Passed)', previousValue: 'Open', newValue: 'Closed' }
    ],
    documents: [
      { id: 'doc-1', name: 'Inspection_Photos_TransitDamage.pdf', type: 'Photo evidence', uploadedBy: 'Technician LDH', uploadedDate: '2026-01-16', status: 'Verified', fileSize: '2.4 MB' },
      { id: 'doc-2', name: 'OEM_Acknowledgement_OEM-TY-2425-001.pdf', type: 'OEM Correspondence', uploadedBy: 'Service Executive', uploadedDate: '2026-01-16', status: 'Verified', fileSize: '1.1 MB' },
      { id: 'doc-3', name: 'GRN_HO_5876_Scan.pdf', type: 'GRN', uploadedBy: 'Stores HO', uploadedDate: '2026-02-05', status: 'Verified', fileSize: '850 KB' },
      { id: 'doc-4', name: 'Credit_Note_TYP_CN_884.pdf', type: 'Credit Note', uploadedBy: 'Finance Dept', uploadedDate: '2026-08-20', status: 'Verified', fileSize: '520 KB' }
    ]
  }),
  base({
    id: 'claim-demo-002',
    claimAgainst: 'Service call',
    callNo: 'SC/MUM/25-26/AMC/000145',
    callDate: '2026-02-25',
    claimDate: '2026-02-27',
    claimNo: 'CLM-TSC-KAN-TY-25-26-001',
    brand: 'Typical',
    customerName: 'Super House Limited',
    model: 'TC-131B 6040HB',
    serialNo: '2102408043',
    partNo: 'DISP-131B',
    description: 'Display Panel Assembly',
    category: 'Performance issue',
    vendorResponse: 'Approved',
    newPartAtHO: 'Y',
    claimChallanNo: 'DN2-2627/MUM1004',
    challanDate: '2026-03-28',
    newPartAtBranch: 'Y',
    turelNewPartOutward: 'Y',
    customerReceiptDate: '2026-03-29',
    oemClaimNo: 'OEM-TY-2425-002',
    oemClaimDate: '2026-02-27',
    oemSettlementExpected: 'Credit Note',
    oemClaimOutcome: 'Pending',
    interimOption: 'A',
    branchTransferRequestNo: 'BTR-KAN-004',
    capaNo: 'CAPA-002',
    capaStatus: 'Open',
    isoClauseRef: 'Cl. 8.4 / 10.2',
    auditLogs: [
      { id: 'log-201', timestamp: '2026-02-27 10:00:00', user: 'Service Head', action: 'Claim Created', previousValue: 'N/A', newValue: 'Created' },
      { id: 'log-202', timestamp: '2026-02-27 11:30:00', user: 'Service Executive', action: 'OEM Claim Raised', previousValue: 'Empty', newValue: 'OEM-TY-2425-002' },
      { id: 'log-203', timestamp: '2026-03-01 14:20:00', user: 'Operations Executive', action: 'Interim Option A Selected', previousValue: 'None', newValue: 'Option A (Stock Transfer)' },
      { id: 'log-204', timestamp: '2026-03-28 16:00:00', user: 'Logistics Desk', action: 'Challan Generated', previousValue: 'Pending', newValue: 'DN2-2627/MUM1004' }
    ],
    documents: [
      { id: 'doc-201', name: 'DisplayPanel_DiagnosticLog.pdf', type: 'Diagnostic report', uploadedBy: 'Technician KAN', uploadedDate: '2026-02-25', status: 'Verified', fileSize: '3.1 MB' },
      { id: 'doc-202', name: 'OEM_Claim_Filing_Form.pdf', type: 'OEM Correspondence', uploadedBy: 'Service Executive', uploadedDate: '2026-02-27', status: 'Verified', fileSize: '1.4 MB' }
    ]
  }),
  base({
    id: 'claim-demo-003',
    claimAgainst: 'Installation call',
    callNo: 'SC/MUM/26-27/AMC/000211',
    callDate: '2026-09-10',
    claimDate: '2026-09-10',
    claimNo: 'CLM-TSC-MUM-TY-26-27-003',
    brand: 'Typical',
    customerName: 'Demo Customer Pvt Ltd',
    model: 'TC-900',
    serialNo: 'DEMO-SN-003',
    partNo: 'CTRL-900',
    description: 'Control Module PCB',
    category: 'DOA – Dead on Arrival',
    oemClaimNo: 'OEM-DEMO-003',
    oemClaimDate: '2026-09-10',
    oemSettlementExpected: 'Replacement',
    auditLogs: [
      { id: 'log-301', timestamp: '2026-09-10 09:00:00', user: 'Service Head', action: 'Claim Created', previousValue: 'N/A', newValue: 'Created' },
      { id: 'log-302', timestamp: '2026-09-10 10:30:00', user: 'Service Executive', action: 'OEM Claim Raised', previousValue: 'Empty', newValue: 'OEM-DEMO-003' }
    ],
    documents: [
      { id: 'doc-301', name: 'DOA_Video_Evidence.mp4', type: 'Video of non-operation', uploadedBy: 'Field Tech', uploadedDate: '2026-09-10', status: 'Verified', fileSize: '14.2 MB' }
    ]
  })
];

export const demoCAPA: CAPA[] = [
  {
    id: 'capa-001',
    capaNo: 'CAPA-001',
    sourceClaimNo: 'CLM-TSC-LDH-TY-25-26-001',
    dateRaised: '2026-01-20',
    nonconformityDescription: 'Oil Tank damaged in transit – packaging inadequate.',
    rootCause5Why: 'No packing checklist for heavy assemblies.',
    correctiveAction: 'Develop packing checklist and retrain Stores team.',
    actionOwner: 'QMS Manager',
    targetDate: '2026-02-28',
    completionDate: '2026-02-20',
    effectivenessCheckDate: '2026-03-20',
    effectivenessVerified: 'Y',
    status: 'Closed',
    isoClause: 'Cl. 8.7 / 10.2'
  },
  {
    id: 'capa-002',
    capaNo: 'CAPA-002',
    sourceClaimNo: 'CLM-TSC-KAN-TY-25-26-001',
    dateRaised: '2026-02-28',
    nonconformityDescription: 'Display Panel QC failure at OEM manufacturing site.',
    rootCause5Why: 'Supplier qualification gap and uncalibrated testing rig.',
    correctiveAction: 'Supplier quality review and incoming inspection protocol.',
    actionOwner: 'Purchase Executive',
    targetDate: '2026-03-31',
    completionDate: '',
    effectivenessCheckDate: '2026-04-30',
    effectivenessVerified: 'Pending',
    status: 'Open',
    isoClause: 'Cl. 8.4 / 10.2'
  }
];
